version: "3.8"
services:
    # rabbitmq3:
    #     container_name: "rabbitmq"
    #     image: rabbitmq:3.8-management-alpine
    #     environment:
    #         - RABBITMQ_DEFAULT_USER=myuser
    #         - RABBITMQ_DEFAULT_PASS=mypassword
    #     ports:
    #         # AMQP protocol port
    #         - '5672:5672'
    #         # HTTP management UI
    #         - '15672:15672'
    #     networks:
    #         - video-service

    testing-video-service:
        build: ./VideoService
        container_name: videoservice.testing
        image: voidbgs/videoservice.testing
        environment:
          ASPNETCORE_ENVIRONMENT: Development
        ports:
            - "7001:80"
        networks:
            - testing-video-service
        restart: on-failure

    # like-service:
    #     build: ./LikeService
    #     container_name: likeservice
    #     image: voidbgs/likeservice
    #     ports:
    #         - "7002:80"
    #     networks:
    #         - video-service
    #     restart: on-failure
    #     depends_on:
    #         - rabbitmq3

    frontend-client:
        build: ./videa-frontend
        container_name: frontendclient.testing
        image: voidbgs/frontendclient
        ports:
            - "80:80"
        networks:
            - testing-video-service
        restart: on-failure
        depends_on:
            - api-gateway

    api-gateway:
        image: nginx:alpine
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.test.conf:ro
        ports:
            - "4000:4000"
        networks:
            - testing-video-service
        depends_on:
            - testing-video-service
    
networks:
    testing-video-service: