version: "3.8"
services:
    rabbitmq3:
        container_name: "rabbitmq"
        image: rabbitmq:3.8-management-alpine
        environment:
            - RABBITMQ_DEFAULT_USER=myuser
            - RABBITMQ_DEFAULT_PASS=mypassword
        ports:
            - '5672:5672'
            - '15672:15672'
        networks:
            - video-service
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:15672"]
            interval: 30s
            timeout: 10s
            retries: 5

    video-service:
        container_name: videoservice
        image: voidbgs/videoservice
        ports:
            - "7001:7001"
        networks:
            - video-service
        restart: on-failure
        depends_on:
            - rabbitmq3

    like-service:
        container_name: likeservice
        image: voidbgs/likeservice
        ports:
            - "7002:7002"
        networks:
            - video-service
        restart: on-failure
        depends_on:
            - rabbitmq3

    frontend-client:
        container_name: frontendclient
        image: voidbgs/frontendclient
        ports:
            - "80:80"
        networks:
            - video-service
        restart: on-failure
        depends_on:
            - rabbitmq3
        
    api-gateway:
        image: nginx:alpine
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        networks:
            - video-service
        ports:
            - "4000:4000"

networks:
    video-service: