name: Build, Test and Push Videa

on:
  push:
    branches: [ main ]

env:
  DOCKER_USER: ${{secrets.USERNAME}}
  DOCKER_PASSWORD: ${{secrets.SESAME}}
  DOTNET_VERSION: '6.0.x'
    
jobs:
  build-set-test-push:
    runs-on: ubuntu-latest
    steps:
      - name: Build the Docker images
        run: docker-compose build
      - name: Log into DockerHub
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Push All Services to DockerHub
        run: docker-compose push
