name: Build, Test and Push Videa

on:
  push:
    branches: [ main ]

env:
  DOCKER_USER: ${{secrets.USERNAME}}
  DOCKER_PASSWORD: ${{secrets.SESAME}}
  DOTNET_VERSION: '6.0.x'
    
jobs:
  build-set-test-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - run: cd VideoService
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Install .NET dependencies
        run: dotnet restore
      - name: Run Video Video Service in developer mode
        run: dotnet run
      - name: Use Node.js 17.x
        uses: actions/setup-node@v1
        with:
          node-version: 17.x
      - name: Install react dependencies
        run: npm install ./videa-frontend
      - name: Run E2E tests
        run: npm test ./videa-frontend
      - name: Build the Docker images
        run: docker-compose build
      - name: Log into DockerHub
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Push All Services to DockerHub
        run: docker-compose push
