name: Build and Push Services

on:
  push:
    branches: [ main ]

env:
  DOCKER_USER: ${{secrets.USERNAME}}
  DOCKER_PASSWORD: ${{secrets.SESAME}}
  DOTNET_VERSION: '6.0.x'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build the Docker images
        run: docker-compose build
      - name: Log into DockerHub
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Push All Services to DockerHub
        run: docker-compose push
  build-and-test:    
    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - name: Change directory
    - run: cd VideoService
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Install dependencies
      run: dotnet restore VideoService
    - name: Build Video Service
      run: dotnet build VideoService --configuration Release --no-restore
    - name: Test Video Service
      run: dotnet test VideoService.Test --no-restore --verbosity normal
