name: Video Service Tests

on: [push]

env:
  DOTNET_VERSION: '6.0.x'
jobs:
  build-and-test:
    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Install dependencies
      run: dotnet restore VideoService.Test/
    - name: Build
      run: dotnet build VideoService.Test/ --configuration Release --no-restore
    - name: Test
      run: dotnet test VideoService.Test/ --no-restore --verbosity normal
